@CommunityBoardAPI_HostAddress = https://localhost:8000


GET {{CommunityBoardAPI_HostAddress}}/api/poster

###


GET {{CommunityBoardAPI_HostAddress}}/api/poster/14

###

POST {{CommunityBoardAPI_HostAddress}}/api/poster
Content-Type: application/json

{
  "title": "dummy poster",
  "description": "Everyone is invided in dummy club, join us"
}

###

DELETE {{CommunityBoardAPI_HostAddress}}/api/poster/9

###
