@SchoolAPI_HostAddress = https://localhost:7000

#Online course Endpoints

# Get all 
GET {{SchoolAPI_HostAddress}}/onlinecourse

###

# Get by id 
GET {{SchoolAPI_HostAddress}}/onlinecourse/4062

###

# Create Online course 
POST {{SchoolAPI_HostAddress}}/onlinecourse
content-type: application/json 

{
  "courseId": 4062,
  "url": "http://www.newMockwebsite"
}

###

PUT {{SchoolAPI_HostAddress}}/onlinecourse/4062
content-type: application/json 

{
  "courseId": 4062,
  "url": "http://www.Mockwebsite/Updated"
}


###

DELETE {{SchoolAPI_HostAddress}}/onlinecourse/999999

###

