@SchoolAPI_HostAddress = https://localhost:7000

# Onsite course Endpoints 


# Get all 
GET {{SchoolAPI_HostAddress}}/onsitecourse

###

# Get by id 
GET {{SchoolAPI_HostAddress}}/onsitecourse/4062

###


# create onsite course 
POST {{SchoolAPI_HostAddress}}/onsitecourse
content-type: application/json

{
  "courseId": 4062,
  "location": "Dummy labroom Craeted",
  "days": "MTWH",
  "time": "1900-01-01T11:30:00"
}

###

# update onsite course 
PUT {{SchoolAPI_HostAddress}}/onsitecourse/4062
content-type: application/json

{
  "courseId": 4062,
  "location": "Dummy labroom updated",
  "days": "MTWH",
  "time": "1900-01-01T11:30:00"
}

###


# delete onsite course 
DELETE {{SchoolAPI_HostAddress}}/onsitecourse/4062

###
