@BasicFruitsAPI_HostAddress = https://localhost:7000

# Get Requests
GET {{BasicFruitsAPI_HostAddress}}/
Accept : application/json
###

GET {{BasicFruitsAPI_HostAddress}}/fruit
Accept : application/json
###


GET {{BasicFruitsAPI_HostAddress}}/fruitlist
Accept : application/json
### 



