# For more info on HTTP files go to https://aka.ms/vs/httpfile

@ConfigurationAPI_HostAdress = https://localhost:7000

# Configuration API Endpoints 

# Get all configurations 
GET {{ConfigurationAPI_HostAdress}}/configurations/all
Accept: application/json

###

# Get UseOne Secrets
GET {{ConfigurationAPI_HostAdress}}/configurations/userOne

###


# Get api key 
GET {{ConfigurationAPI_HostAdress}}/configurations/apikey

###

# Get mock configuration
GET {{ConfigurationAPI_HostAdress}}/configurations/mockconfiguration

###
