@RecipeMinimalAPI_HostAddress = https://localhost:7000

# Home
GET {{RecipeMinimalAPI_HostAddress}}/
Accept: application/json

### 

# Endpoint Does not exists
GET {{RecipeMinimalAPI_HostAddress}}/unknown
Accept: application/json

### 

# Throw Exception
GET {{RecipeMinimalAPI_HostAddress}}/throwException
Accept: application/json

###


# Recipe API Endpoints 


# GET Methods 

# Get all Recipies
GET {{RecipeMinimalAPI_HostAddress}}/recipe/all
Accept: application/json

###

# Get Recipe by ID 
GET {{RecipeMinimalAPI_HostAddress}}/recipe/1
Accept: application/json

###
